apiVersion: v1
kind: Pod
metadata:
  name: crypto-sidecar-pod
  labels:
    app: crypto-sidecar
spec:
  containers:
    - name: client-service
      image: crypto-sidecar/client-service:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: default
        - name: SIDECAR_REST_BASE_URL
          value: http://localhost:8081
        - name: GRPC_CLIENT_CRYPTOSIDECAR_ADDRESS
          value: static://localhost:9090
    - name: sidecar-service
      image: crypto-sidecar/sidecar-service:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8081
        - containerPort: 9090
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: default
        - name: SERVER_PORT
          value: "8081"
        - name: GRPC_SERVER_PORT
          value: "9090"
